version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
      POSTGRES_DB: prices
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
