name: general-rust-ci
run-name: ${{github.ref_name}}-${{ github.actor }}-ci

on: [push]

permissions:
  contents: read

jobs:
  test:
    runs-on: [ubuntu-22.04]
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install rust
        uses: brndnmtthws/rust-action-rustup@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
      - name: Set SQLX_OFFLINE environment variable
        run: echo "SQLX_OFFLINE=true" >> $GITHUB_ENV
      - name: test
        run: cargo test
